analyze -library WORK \
  -format sverilog " \
$VERILOG_DIR/top/synthesis_defines.v \
$VERILOG_DIR/top/defines.v \
$VERILOG_DIR/top/user_defines.v \
$VERILOG_DIR/top/pads.wire.v \
$VERILOG_DIR/top/fsic_iopad.v \
$VERILOG_DIR/top/sky130_fd_sc.v \
$VERILOG_DIR/top/RAM256.v \
$VERILOG_DIR/top/RAM128.v \
$VERILOG_DIR/top/spram.wire.v \
$VERILOG_DIR/top/Sram.v \
$VERILOG_DIR/top/sram_wrapper.v \
$VERILOG_DIR/top/buff_flash_clkrst.wire.v \
$VERILOG_DIR/caravel/caravel_top.v \
$VERILOG_DIR/caravel/caravel_clocking.wire.v \ 
$VERILOG_DIR/caravel/caravel_logo.wire.v \
$VERILOG_DIR/caravel/caravel_motto.wire.v \
$VERILOG_DIR/caravel/caravel_power_routing.wire.v \
$VERILOG_DIR/caravel/chip_io.wire.v \
$VERILOG_DIR/caravel/reset_as_por.v \
$VERILOG_DIR/caravel/xres_buf.wire.v \
$VERILOG_DIR/caravel/VexRiscv_MinDebug.v \
$VERILOG_DIR/caravel/gpio_control_block.wire.v \
$VERILOG_DIR/caravel/gpio_defaults_block.wire.v \
$VERILOG_DIR/caravel/gpio_logic_high.wire.v \
$VERILOG_DIR/caravel/gpio_signal_buffering.wire.v \
$VERILOG_DIR/caravel/housekeeping_spi.v \
$VERILOG_DIR/caravel/housekeeping.wire.v \
$VERILOG_DIR/caravel/manual_power_connections.v \
$VERILOG_DIR/caravel/mgmt_core.vic.v \
$VERILOG_DIR/caravel/mgmt_core_wrapper.wire.v \
$VERILOG_DIR/caravel/mgmt_protect.wire.v \
$VERILOG_DIR/caravel/mprj_io_buffer.wire.v \ 
$VERILOG_DIR/caravel/mprj_io.wire.v \
$VERILOG_DIR/caravel/user_project_wrapper.v \
$VERILOG_DIR/caravel/open_source.wire.v \
$VERILOG_DIR/caravel/constant_block.wire.v \
$VERILOG_DIR/caravel/copyright_block.wire.v \
$VERILOG_DIR/caravel/empty_macro.v \
$VERILOG_DIR/fsic/fsic.v \
$VERILOG_DIR/fsic/fsic_clkrst.v \
$VERILOG_DIR/fsic/fsic_coreclk_phase_cnt.v \
$VERILOG_DIR/fsic/fsic_io_serdes_rx.v \
$VERILOG_DIR/fsic/fsic_mprj_io.v \
$VERILOG_DIR/fsic/io_serdes.v \
$VERILOG_DIR/fsic/irq_mux.v \
$VERILOG_DIR/fsic/la_mux.v \
$VERILOG_DIR/fsic/sw_caravel.v \
$VERILOG_DIR/fsic/LogicAnalyzer.v \
$VERILOG_DIR/fsic/config_ctrl.v \
$VERILOG_DIR/fsic/axil_axis.v \
$VERILOG_DIR/fsic/axil_slav.v \
$VERILOG_DIR/fsic/axis_mstr.v \
$VERILOG_DIR/fsic/axis_slav.v \
$VERILOG_DIR/user_project/user_id_programming.wire.v \
$VERILOG_DIR/user_project/user_id_textblock.wire.v \
$VERILOG_DIR/user_project/user_subsys.v \
$VERILOG_DIR/user_project/user_prj0.v \
$VERILOG_DIR/user_project/user_prj1.v \
$VERILOG_DIR/user_project/user_prj2.v \
$VERILOG_DIR/user_project/user_prj3.v \
$VERILOG_DIR/user_project/concat_EdgeDetect_Top_fsic.v "