#!/bin/csh -f
setenv ICV_HOME_DIR /global/apps/icv_2022.12-SP5/
setenv ICVWB_HOME_DIR /global/apps/icvwb_2022.12-SP2/
setenv PATH $ICV_HOME_DIR/bin:$PATH



## User setting ##
setenv block_spice "../../../SAED14_EDK_LAB/lib/stdcell_rvt/hspice/saed14nm_rvt.spf"
setenv block_lef "../../../SAED14_EDK_LAB/lib/stdcell_rvt/lef/saed14nm_rvt_1p9m.lef"

##
set block = i2c_master_top
setenv spice_block_name $block
setenv gds_block_name `echo $block | awk '{print toupper($0)}'`
setenv block_gds "../../results/i2c_master_top.gds"

egrep "^MACRO " $block_lef | awk '{print "	{\""$2"\", \""$2"\"}"","}' | sed '1 s/^/equiv_options(\n/g' | sed '$ s/},/}\n }\n);g' 

rm -rf *.vue *.LAYOUT_ERRORS *.RESULTS run_details icv.log
icv -host_init 16 -vue \
-c $gds_block_name \
-i $block_gds \
-stc $spice_block_name \
-s $block_spice \
-sf SPICE
-vueshortALL \
-create_lvs_short_outputALL \
-e ./user.equiv \
-ex \
-elpc 10000 \






