../../rtl/top/defines.v 
../../rtl/top/synthesis_define.v.t18
../../rtl/top/user_defines.v
../../rtl/top/pads_config.v
../../rtl/top/RAM256.v
../../rtl/top/RAM128.v 
../../rtl/top/sram_wrapper.v
../../rtl/caravel/caravel_top.v
../../rtl/caravel/gpio_defaults_block.v
../../rtl/caravel/gpio_control_block.v
../../rtl/caravel/housekeeping.v
../../rtl/caravel/housekeeping_spi.v
../../rtl/caravel/mgmt_core.v
../../rtl/caravel/mgmt_core_wrapper.v
../../rtl/caravel/mprj_io.v
../../rtl/caravel/VexRiscv_MinDebugCache.v
../../rtl/fsic/fsic.v 
../../rtl/fsic/fsic_clkrst.v 
../../rtl/fsic/fsic_coreclk_phase_cnt.v 
../../rtl/fsic/fsic_io_serdes_rx.v 
../../rtl/fsic/fsic_mprj_io.v 
../../rtl/fsic/io_serdes.v 
../../rtl/fsic/irq_mux.v 
../../rtl/fsic/la_mux.v 
../../rtl/fsic/sw_caravel.v 
../../rtl/fsic/LogicAnalyzer.v 
../../rtl/fsic/config_ctrl.v 
../../rtl/fsic/axil_axis.v 
../../rtl/fsic/axil_slav.v 
../../rtl/fsic/axis_mstr.v 
../../rtl/fsic/axis_slav.v 
../../rtl/fsic/fifo.v 
../../rtl/user_project/user_project_wrapper.v
../../rtl/user_project/user_subsys.v 
../../rtl/user_project/user_prj0.v 
../../rtl/user_project/user_prj1.v 
../../rtl/user_project/user_prj2.v 
../../rtl/user_project/user_prj3.v 
../../rtl/user_project/concat_EdgeDetect_Top_fsic.v 
../../rtl/user_project/falcon_In_copy.v 
../../rtl/user_project/falcon_stage.v 