top_bench.sv
../../rtl/top/defines.v 
../../rtl/top/user_defines.v 
../../rtl/top/pads.wire.v 
../../rtl/top/fsic_iopad.v 
../../rtl/top/sky130_fd_sc.v 
../../rtl/top/RAM256.v 
../../rtl/top/RAM128.v 
../../rtl/top/spram.wire.v 
../../rtl/top/Sram.v 
../../rtl/top/sram_wrapper.v
../../rtl/top/buff_flash_clkrst.wire.v 
../../rtl/caravel/caravel_top.v 
../../rtl/caravel/caravel_clocking.wire.v 
../../rtl/caravel/caravel_logo.wire.v 
../../rtl/caravel/caravel_motto.wire.v 
../../rtl/caravel/caravel_power_routing.wire.v 
../../rtl/caravel/chip_io.wire.v 
../../rtl/caravel/reset_as_por.v 
../../rtl/caravel/VexRiscv_MinDebug.v 
../../rtl/caravel/gpio_control_block.wire.v 
../../rtl/caravel/gpio_defaults_block.wire.v 
../../rtl/caravel/gpio_logic_high.wire.v 
../../rtl/caravel/gpio_signal_buffering.wire.v 
../../rtl/caravel/housekeeping_spi.v 
../../rtl/caravel/housekeeping.wire.v 
../../rtl/caravel/manual_power_connections.v 
../../rtl/caravel/mgmt_core.vic.v 
../../rtl/caravel/mgmt_core_wrapper.wire.v 
../../rtl/caravel/mgmt_protect.wire.v 
../../rtl/caravel/mprj_io_buffer.wire.v 
../../rtl/caravel/mprj_io.wire.v 
../../rtl/caravel/user_project_wrapper.v 
../../rtl/caravel/open_source.wire.v 
../../rtl/caravel/constant_block.wire.v 
../../rtl/caravel/copyright_block.wire.v 
../../rtl/caravel/empty_macro.v 
../../rtl/fsic/fsic.v 
../../rtl/fsic/fsic_clkrst.v 
../../rtl/fsic/fsic_coreclk_phase_cnt.v 
../../rtl/fsic/fsic_io_serdes_rx.v 
../../rtl/fsic/fsic_mprj_io.v 
../../rtl/fsic/io_serdes.v 
../../rtl/fsic/irq_mux.v 
../../rtl/fsic/la_mux.v 
../../rtl/fsic/sw_caravel.v 
../../rtl/fsic/LogicAnalyzer.v 
../../rtl/fsic/config_ctrl.v 
../../rtl/fsic/axil_axis.v 
../../rtl/fsic/axil_slav.v 
../../rtl/fsic/axis_mstr.v 
../../rtl/fsic/axis_slav.v 
../../rtl/user_project/user_id_programming.wire.v 
../../rtl/user_project/user_id_textblock.wire.v 
../../rtl/user_project/user_subsys.v 
../../rtl/user_project/user_prj0.v 
../../rtl/user_project/user_prj1.v 
../../rtl/user_project/user_prj2.v 
../../rtl/user_project/user_prj3.v 
../../rtl/user_project/concat_EdgeDetect_Top_fsic.v 