//****************************************************************************//
// Verilog models generated by SiliconSmart M-2017.03-SP3 build date: Aug 22, 2017 15:59:14. (SMSC-2) //
// Siliconsmart Path: /global/apps/siliconsmart_2017.03-SP3/linux64/bin/siliconsmart //
// Host Name: am04dwamd079.internal.synopsys.com, User Name: saroyan, PID: 10564  //
// Directory: /remote/saed/meruzha/char_io/fc/processes/tt0p8v25c_1p8v/siliconsmart/simulation_fc //
//                                                                            //
// File generated on Wed Dec 13 20:48:21 AMT 2017. (SMSC-3)                   //
//****************************************************************************//


`timescale 1ns/1ps



`celldefine
module A1825_EW_func( CORE, PADIO );
   inout CORE, PADIO;

endmodule
`endcelldefine


`celldefine
module A1825_NS_func( CORE, PADIO );
   inout CORE, PADIO;

endmodule
`endcelldefine


`celldefine
module AR1825_EW_func( CORE, PADIO );
   inout CORE, PADIO;

endmodule
`endcelldefine


`celldefine
module AR1825_NS_func( CORE, PADIO );
   inout CORE, PADIO;

endmodule
`endcelldefine


`celldefine
module AVDD_EW_func(  );

endmodule
`endcelldefine


`celldefine
module AVDD_NS_func(  );

endmodule
`endcelldefine


`celldefine
module AVSS_EW_func(  );

endmodule
`endcelldefine


`celldefine
module AVSS_NS_func(  );

endmodule
`endcelldefine


`celldefine
module B12I1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B12I1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B12ISH1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B12ISH1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B16I1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B16I1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B16ISH1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B16ISH1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B4I1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B4I1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B4ISH1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B4ISH1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B8I1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B8I1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B8ISH1025_EW_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module B8ISH1025_NS_func( DIN, DOUT, EN, PADIO, PULL_DOWN, PULL_UP, R_EN );
   input DIN, EN, PULL_DOWN, PULL_UP, R_EN;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, EN );
   not MGM_BG_2( MGM_WB_1, EN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module BONDPAD_func( PADIO );
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module CORNER_func(  );

endmodule
`endcelldefine


`celldefine
module D12I1025_EW_func( DIN, EN, PADIO );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module D12I1025_NS_func( DIN, EN, PADIO );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module D16I1025_EW_func( DIN, EN, PADIO );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module D16I1025_NS_func( DIN, EN, PADIO );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module D4I1025_EW_func( PADIO, DIN, EN );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module D4I1025_NS_func( DIN, EN, PADIO );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module D8I1025_EW_func( DIN, EN, PADIO );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module D8I1025_NS_func( DIN, EN, PADIO );
   input DIN, EN;
   inout PADIO;

endmodule
`endcelldefine


`celldefine
module FILLER_func(  );

endmodule
`endcelldefine


`celldefine
module FILLER01_func(  );

endmodule
`endcelldefine


`celldefine
module FILLER1_func(  );

endmodule
`endcelldefine


`celldefine
module FILLER5_func(  );

endmodule
`endcelldefine


`celldefine
module HSTL_EW_func( DIN, DOUT, PADIO, R_EN, TEN, VREF );
   input DIN, R_EN, TEN, VREF;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, TEN );
   not MGM_BG_2( MGM_WB_1, TEN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module HSTL_NS_func( DIN, DOUT, PADIO, R_EN, TEN, VREF );
   input DIN, R_EN, TEN, VREF;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, TEN );
   not MGM_BG_2( MGM_WB_1, TEN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module I1025_EW_func( DOUT, PADIO, R_EN );
   input PADIO, R_EN;
   output DOUT;
   and MGM_BG_0( DOUT, PADIO, R_EN );

endmodule
`endcelldefine


`celldefine
module I1025_NS_func( DOUT, PADIO, R_EN );
   input PADIO, R_EN;
   output DOUT;
   and MGM_BG_0( DOUT, PADIO, R_EN );

endmodule
`endcelldefine


`celldefine
module IOVDD_EW_func(  );

endmodule
`endcelldefine


`celldefine
module IOVDD_NS_func(  );

endmodule
`endcelldefine


`celldefine
module IOVSS_EW_func(  );

endmodule
`endcelldefine


`celldefine
module IOVSS_NS_func(  );

endmodule
`endcelldefine


`celldefine
module ISH1025_EW_func( DOUT, PADIO, R_EN );
   input PADIO, R_EN;
   output DOUT;
   and MGM_BG_0( DOUT, PADIO, R_EN );

endmodule
`endcelldefine


`celldefine
module ISH1025_NS_func( DOUT, PADIO, R_EN );
   input PADIO, R_EN;
   output DOUT;
   and MGM_BG_0( DOUT, PADIO, R_EN );

endmodule
`endcelldefine


`celldefine
module SSTL_EW_func( DIN, DOUT, PADIO, R_EN, TEN, VREF );
   input DIN, R_EN, TEN, VREF;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, TEN );
   not MGM_BG_2( MGM_WB_1, TEN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module SSTL_NS_func( DIN, DOUT, PADIO, R_EN, TEN, VREF );
   input DIN, R_EN, TEN, VREF;
   output DOUT;
   inout PADIO;
   and MGM_BG_0( DOUT, PADIO, R_EN );
   wire MGM_WB_0;
   wire MGM_WB_1;
   and MGM_BG_1( MGM_WB_0, DIN, TEN );
   not MGM_BG_2( MGM_WB_1, TEN );
   bufif0 MGM_BG_3( PADIO, MGM_WB_0,MGM_WB_1 );

endmodule
`endcelldefine


`celldefine
module VDD_EW_func(  );

endmodule
`endcelldefine


`celldefine
module VDD_NS_func(  );

endmodule
`endcelldefine


`celldefine
module VSS_EW_func(  );

endmodule
`endcelldefine


`celldefine
module VSS_NS_func(  );

endmodule
`endcelldefine
