cpp -P ./user_project/falcon_stage.v falcon_stage.v
cpp -P ./caravel/caravel.v caravel.v
cat \
top/defines.v \
top/user_defines.v \
top/pads_config.v \
top/RAM256.v \
top/RAM128.v \
caravel.v \
caravel/housekeeping.vic.v \
caravel/housekeeping_spi.v \
caravel/mgmt_core.vic.v \
caravel/mgmt_core_wrapper.v \
caravel/mprj_io.v \
caravel/VexRiscv_MinDebugCache.v \
fsic/fsic.v \
fsic/fsic_clkrst.v \
fsic/fsic_coreclk_phase_cnt.v \
fsic/fsic_io_serdes_rx.v \
fsic/fsic_mprj_io.v \
fsic/io_serdes.v \
fsic/irq_mux.v \
fsic/la_mux.v \
fsic/sw_caravel.v \
fsic/LogicAnalyzer.v \
fsic/config_ctrl.v \
fsic/axil_axis.v \
fsic/axil_slav.v \
fsic/axis_mstr.v \
fsic/axis_slav.v \
fsic/fifo.v \
user_project/user_project_wrapper.v \
user_project/user_subsys.v \
user_project/user_prj0.v \
user_project/user_prj1.v \
user_project/user_prj2.v \
user_project/user_prj3.v \
user_project/concat_EdgeDetect_Top_fsic.v \
user_project/falcon_In_copy.v \
falcon_stage.v \
> caravel_chip.v
rm falcon_stage.v
rm caravel.v