suppress_message LINT-1
unalias cpu_isle
suppress_message LINT-2
unalias cpu_isle
suppress_message LINT-1
unalias hif2bt
suppress_message LINT-28
unalias sys_clk_sync 
unalias hosif 
suppress_message LINT-29
unalias sync_regs 
suppress_message LINT-29
unalias iccm_control 
suppress_message LINT-31
unalias debug_port 
suppress_message LINT-32
suppress_message LINT-33
suppress_message LINT-52
suppress_message LINT-55
